openapi: 3.0.0
info:
  title: UNIverse University API
  description: |
    University management API for the UNIverse platform.
    This API provides endpoints for managing universities, faculties, departments, and related operations.
  version: 1.0.0
  contact:
    name: UNIverse Support
    email: support@universe.com

servers:
  - url: https://universe-backend-kpry.onrender.com/api
    description: Production server
  - url: http://localhost:5000/api
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    University:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the university
        name:
          type: string
          description: Name of the university
        description:
          type: string
          description: Detailed description of the university
        location:
          type: object
          properties:
            country:
              type: string
              description: Country where the university is located
            city:
              type: string
              description: City where the university is located
            address:
              type: string
              description: Full address of the university
        logo:
          type: object
          properties:
            url:
              type: string
              format: uri
              description: URL of the university logo
            publicId:
              type: string
              description: Cloudinary public ID of the logo
        website:
          type: string
          format: uri
          description: Official website URL of the university
        email:
          type: string
          format: email
          description: Official contact email of the university
        phone:
          type: string
          description: Official contact phone number
        faculties:
          type: array
          items:
            $ref: '#/components/schemas/Faculty'
        createdAt:
          type: string
          format: date-time
          description: When the university was added to the platform
        updatedAt:
          type: string
          format: date-time
          description: When the university was last updated

    Faculty:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the faculty
        name:
          type: string
          description: Name of the faculty
        description:
          type: string
          description: Detailed description of the faculty
        departments:
          type: array
          items:
            $ref: '#/components/schemas/Department'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Department:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the department
        name:
          type: string
          description: Name of the department
        description:
          type: string
          description: Detailed description of the department
        studyLevels:
          type: array
          items:
            type: string
            enum: [undergraduate, graduate, PhD]
          description: Available study levels in the department
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message

    Success:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          description: Success message

paths:
  /universities:
    get:
      tags:
        - Universities
      summary: Get all universities
      description: Retrieve a list of all universities with optional filtering
      parameters:
        - name: search
          in: query
          description: Search universities by name or description
          schema:
            type: string
        - name: country
          in: query
          description: Filter universities by country
          schema:
            type: string
        - name: city
          in: query
          description: Filter universities by city
          schema:
            type: string
      responses:
        '200':
          description: List of universities retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  universities:
                    type: array
                    items:
                      $ref: '#/components/schemas/University'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Universities
      summary: Create a new university
      description: Create a new university (Admin only)
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - description
                - country
                - city
              properties:
                name:
                  type: string
                description:
                  type: string
                country:
                  type: string
                city:
                  type: string
                address:
                  type: string
                website:
                  type: string
                  format: uri
                email:
                  type: string
                  format: email
                phone:
                  type: string
                logo:
                  type: string
                  format: binary
      responses:
        '201':
          description: University created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  university:
                    $ref: '#/components/schemas/University'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /universities/{universityId}:
    get:
      tags:
        - Universities
      summary: Get university details
      description: Retrieve detailed information about a specific university
      parameters:
        - name: universityId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: University details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  university:
                    $ref: '#/components/schemas/University'
        '404':
          description: University not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - Universities
      summary: Update university details
      description: Update university information (Admin only)
      security:
        - BearerAuth: []
      parameters:
        - name: universityId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                country:
                  type: string
                city:
                  type: string
                address:
                  type: string
                website:
                  type: string
                  format: uri
                email:
                  type: string
                  format: email
                phone:
                  type: string
                logo:
                  type: string
                  format: binary
      responses:
        '200':
          description: University updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  university:
                    $ref: '#/components/schemas/University'
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: University not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Universities
      summary: Delete university
      description: Delete a university (Admin only)
      security:
        - BearerAuth: []
      parameters:
        - name: universityId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: University deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: University not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /universities/{universityId}/faculties:
    get:
      tags:
        - Faculties
      summary: Get university faculties
      description: Retrieve all faculties of a specific university
      parameters:
        - name: universityId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Faculties retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  faculties:
                    type: array
                    items:
                      $ref: '#/components/schemas/Faculty'
        '404':
          description: University not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Faculties
      summary: Add faculty to university
      description: Add a new faculty to a university (Admin only)
      security:
        - BearerAuth: []
      parameters:
        - name: universityId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Faculty added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  faculty:
                    $ref: '#/components/schemas/Faculty'
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: University not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /universities/{universityId}/faculties/{facultyId}/departments:
    get:
      tags:
        - Departments
      summary: Get faculty departments
      description: Retrieve all departments of a specific faculty
      parameters:
        - name: universityId
          in: path
          required: true
          schema:
            type: string
        - name: facultyId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Departments retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  departments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Department'
        '404':
          description: University or faculty not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Departments
      summary: Add department to faculty
      description: Add a new department to a faculty (Admin only)
      security:
        - BearerAuth: []
      parameters:
        - name: universityId
          in: path
          required: true
          schema:
            type: string
        - name: facultyId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - studyLevels
              properties:
                name:
                  type: string
                description:
                  type: string
                studyLevels:
                  type: array
                  items:
                    type: string
                    enum: [undergraduate, graduate, PhD]
      responses:
        '201':
          description: Department added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  department:
                    $ref: '#/components/schemas/Department'
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: University or faculty not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
